language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
services:
  - docker
script:
  - docker build -t miniweather_web .
  - docker tag miniweather_web thesinner/miniweather_web
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - docker push thesinner/miniweather_web
on:
  branch: master